services:
  - type: web
    name: farpy-admin-web
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 4000
      - key: ADMIN_API_TOKEN
        sync: false
      - key: LINK_SIGNING_SECRET
        sync: false
      - key: BUNNY_PULL_BASE
        sync: false
      - key: PUBLIC_BASE
        sync: false
